version: "3.9"

services:
#  api:
#    build:
#      context: .
#      dockerfile : docker/python/Dockerfile
#    container_name: fastapi-api
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    environment:
#      DATABASE_URL: postgresql+psycopg://fastapi:fastapi@db:5432/ecommerce
#    depends_on:
#      - db

  db:
    image: postgres:16
    container_name: fastapi-db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
